### ISSUE TITLE
idea 

### ISSUE THREAD

**Issue by jacklmarsoul** [NazeemNato/Flutter-Random-Quote-App#1]
Hi sir ,
can you make another project but with api 
not local file json 
like this : https://run.mocky.io/v3/1649bd7b-1fb3-44fe-83a6-2c529afb112d

**Comment by NazeemNato** [comment]
ye

> Hi sir ,
> can you make another project but with api
> not local file json
> like this : https://run.mocky.io/v3/1649bd7b-1fb3-44fe-83a6-2c529afb112d

yes yes

**Comment by NazeemNato** [comment]
> Hi sir ,
> can you make another project but with api
> not local file json
> like this : https://run.mocky.io/v3/1649bd7b-1fb3-44fe-83a6-2c529afb112d

Hey please check this repo 

https://github.com/NazeemNato/Random-quotes-app-using-api
